#!/bin/bash

url=$1

green='\033[1;32m'
cyan='\033[1;36m'
white='\033[1;37m'
red='\033[1;31m'
reset='\033[0m'
bar="$green—————————————————————————$reset"

echo -e "\n${cyan}[*]${white} Termux Downloader by ${cyan}haiueom${reset}"
echo "${bar}"
echo -e "${cyan}[!]${white} URL${red}:${white} ${green}${url}${reset}"
echo "${bar}"
echo -e "${cyan}[!]${white} Available Options${reset}"
echo -e "${white}  1: Download mp4 (video)${reset}"
echo -e "${white}  2: Download mkv (video)${reset}"
echo -e "${white}  3: Download mp3 (audio)${reset}"
echo -e "${white}  4: Download mp4 & mp3${reset}"
echo -e "${white}  5: Download mkv & mp3${reset}"
echo -e "${white}  6: Download with wget${reset}"
echo -e "${white}  x: Exit${reset}"
echo "${bar}"
echo -e "${cyan}[*]${white} Choose an option: "

read -r option

echo -e "${bar}\n"

case $option in
    1)
        yt-dlp -f 'bv[height<=?1080]+ba/b' --merge-output-format 'mp4' "$url"
    ;;
    2)
        yt-dlp -f 'bv[height<=?1080]+ba/b' --merge-output-format 'mkv' "$url"
    ;;
    3)
        yt-dlp -f 'ba' -x --audio-format --audio-quality 0 'mp3' "$url"
    ;;
    4)
        yt-dlp -f 'bv[height<=?1080]+ba/b' --merge-output-format 'mp4' "$url"
        yt-dlp -f 'ba' -x --audio-format --audio-quality 0 'mp3' "$url"
    ;;
    5)
        yt-dlp -f 'bv[height<=?1080]+ba/b' --merge-output-format 'mkv' "$url"
        yt-dlp -f 'ba' -x --audio-format --audio-quality 0 'mp3' "$url"
    ;;
    6)
        [ -d "$HOME/storage/downloads/termux/wget" ] || mkdir "$HOME/storage/downloads/termux/wget"
        cd "$HOME/storage/downloads/termux/wget" || exit
        wget "$url"
    ;;
    x)
        echo "bye . . ."
    ;;
esac
